# Generated by Django 3.1.2 on 2020-10-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailApp', '0003_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=200)),
                ('branch_code', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
